### ISSUE TITLE
Trap in fxwrap.sys

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/InJoy#45]
![img_2778](https://cloud.githubusercontent.com/assets/1235738/16922392/9b5f1dd4-4d15-11e6-91a2-1a0e7f457f12.jpg)

For this issue we already have a testfix. So if one sees the same, please let us know.

**Comment by ydario** [comment]
See http://trac.bitwiseworks.com/injoy/ticket/20 for details.

This has been fixed in changeset 9255.

**Comment by AndiB-2** [comment]
I see a TRAP 000d with same EIP address. Other values differ. Is this the same?

This is on a headless system which worked since a few months without problems. Usually more than 10h a day. Without traps/reboot. Since this morning I see the trap every time a few seconds after pmshell comes up probably at the same time or a few seconds after gateway is started. 

If I ever find out how to add a jpeg to this ticket with our SM on OS/2 I'll attach the tap screen here.

**Comment by SilvanScherrer** [comment]
I will send you anew fxwrap next week.
